cd ${{ vars.PROD_PATH }}

chown -R ${{ secrets.USER_NAME }}:${{ secrets.USER_NAME }} .

truncate -s 0 storage/logs/laravel.log || true
truncate -s 0 storage/logs/queue.log || true

su - ${{ secrets.USER_NAME }} -c "
cd '${{ vars.PROD_PATH }}' &&
git config --global --add safe.directory '${{ vars.PROD_PATH }}' &&
git checkout master &&
git reset --hard &&
git pull &&
rm -f composer.lock
"

cp deploy/queue-worker.conf /etc/supervisor/conf.d/${{ secrets.USER_NAME }}.conf

(service supervisor status >/dev/null 2>&1 || service supervisor start || supervisord -c /etc/supervisord.conf)

sleep 2
supervisorctl reread
supervisorctl update
service supervisor restart
